name: 'Build & Push Docker Image'
description: 'Pushes a Docker image to a ghcr.io registry'

inputs:
  github_token:
    description: 'GitHub Token for GHCR login'
    required: true

outputs:
  image:
    description: 'Pushed image tag'

runs:
  using: "composite"
  steps:
    - name: Docker build & push
      run: node $GITHUB_ACTION_PATH/image-push.js
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
