name: 'Build & Push Docker Image'
description: 'Pushes a Docker image to a ghcr.io registry'

inputs:
  github_token:
    description: 'GitHub Token for GHCR login'
    required: true
  image_name:
    description: 'Image name'
    required: true

outputs:
  image:
    description: 'Pushed image tag'

runs:
  using: "node16"
  main: "image-push.js"
