name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker build and push action
        uses: ./.github/actions/docker-build
        with:
          image_name: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
