name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Run build-push action
        uses: ./.github/actions/image-push/image-push.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
